<?php 


/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class PluginPage {
	private $plugin_page_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'plugin_page_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'plugin_page_page_init' ) );
	}

	public function plugin_page_add_plugin_page() {
		add_options_page(
			'Plugin Page', // page_title
			'Plugin Page', // menu_title
			'manage_options', // capability
			'plugin-page', // menu_slug
			array( $this, 'plugin_page_create_admin_page' ) // function
		);
	}

	public function plugin_page_create_admin_page() {
		$this->plugin_page_options = get_option( 'plugin_page_option_name' ); ?>

		<div class="wrap">
			<h2>Plugin Page</h2>
			<p>some description</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
				settings_fields( 'plugin_page_option_group' );
				do_settings_sections( 'plugin-page-admin' );
				submit_button();
				?>
			</form>
		</div>
	<?php }

	public function plugin_page_page_init() {
		register_setting(
			'plugin_page_option_group', // option_group
			'plugin_page_option_name', // option_name
			array( $this, 'plugin_page_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'plugin_page_setting_section', // id
			'Settings', // title
			array( $this, 'plugin_page_section_info' ), // callback
			'plugin-page-admin' // page
		);

		add_settings_field(
			'first_name_0', // id
			'First Name', // title
			array( $this, 'first_name_0_callback' ), // callback
			'plugin-page-admin', // page
			'plugin_page_setting_section' // section
		);

		add_settings_field(
			'last_name_1', // id
			'Last Name', // title
			array( $this, 'last_name_1_callback' ), // callback
			'plugin-page-admin', // page
			'plugin_page_setting_section' // section
		);

		add_settings_field(
			'message_2', // id
			'Message', // title
			array( $this, 'message_2_callback' ), // callback
			'plugin-page-admin', // page
			'plugin_page_setting_section' // section
		);

		add_settings_field(
			'gender_3', // id
			'Gender', // title
			array( $this, 'gender_3_callback' ), // callback
			'plugin-page-admin', // page
			'plugin_page_setting_section' // section
		);

		add_settings_field(
			'agree_4', // id
			'agree?', // title
			array( $this, 'agree_4_callback' ), // callback
			'plugin-page-admin', // page
			'plugin_page_setting_section' // section
		);
	}

	public function plugin_page_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['first_name_0'] ) ) {
			$sanitary_values['first_name_0'] = sanitize_text_field( $input['first_name_0'] );
		}

		if ( isset( $input['last_name_1'] ) ) {
			$sanitary_values['last_name_1'] = sanitize_text_field( $input['last_name_1'] );
		}

		if ( isset( $input['message_2'] ) ) {
			$sanitary_values['message_2'] = esc_textarea( $input['message_2'] );
		}

		if ( isset( $input['gender_3'] ) ) {
			$sanitary_values['gender_3'] = $input['gender_3'];
		}

		if ( isset( $input['agree_4'] ) ) {
			$sanitary_values['agree_4'] = $input['agree_4'];
		}

		return $sanitary_values;
	}

	public function plugin_page_section_info() {
		echo "testing";
	}

	public function first_name_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="plugin_page_option_name[first_name_0]" id="first_name_0" value="%s">',
			isset( $this->plugin_page_options['first_name_0'] ) ? esc_attr( $this->plugin_page_options['first_name_0']) : ''
		);
	}

	public function last_name_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="plugin_page_option_name[last_name_1]" id="last_name_1" value="%s">');
	}

	public function message_2_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="plugin_page_option_name[message_2]" id="message_2">%s</textarea>',
			isset( $this->plugin_page_options['message_2'] ) ? esc_attr( $this->plugin_page_options['message_2']) : ''
		);
	}

	public function gender_3_callback() {
		?> <select name="plugin_page_option_name[gender_3]" id="gender_3">
			<?php $selected = (isset( $this->plugin_page_options['gender_3'] ) && $this->plugin_page_options['gender_3'] === 'option-one') ? 'selected' : '' ; ?>
			<option value="option-one" <?php echo $selected; ?>>Male</option>
			<?php $selected = (isset( $this->plugin_page_options['gender_3'] ) && $this->plugin_page_options['gender_3'] === 'option-two') ? 'selected' : '' ; ?>
			<option value="option-two" <?php echo $selected; ?>>Female</option>
			</select> <?php
		}

		public function agree_4_callback() {
			printf(
				'<input type="checkbox" name="plugin_page_option_name[agree_4]" id="agree_4" value="agree_4" %s>',
				( isset( $this->plugin_page_options['agree_4'] ) && $this->plugin_page_options['agree_4'] === 'agree_4' ) ? 'checked' : ''
			);
		}

	}


new PluginPage();
	
/* 
 * Retrieve this value with:
 * $plugin_page_options = get_option( 'plugin_page_option_name' ); // Array of All Options
 * $first_name_0 = $plugin_page_options['first_name_0']; // First Name
 * $last_name_1 = $plugin_page_options['last_name_1']; // Last Name
 * $message_2 = $plugin_page_options['message_2']; // Message
 * $gender_3 = $plugin_page_options['gender_3']; // Gender
 * $agree_4 = $plugin_page_options['agree_4']; // agree?
 */
